# Generated by Django 2.0 on 2022-03-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentuser',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
