# Generated by Django 2.0 on 2022-03-13 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220312_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='image',
            new_name='doc',
        ),
    ]
