# Generated by Django 2.0 on 2022-03-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220313_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoruser',
            name='amount',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contractoruser',
            name='quot_doc',
            field=models.FileField(max_length=20, null=True, upload_to=''),
        ),
    ]
