# Generated by Django 2.0 on 2022-03-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220313_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoruser',
            name='contr',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
